#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2025 Microsoft Corporation
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public
# License as published by the Free Software Foundation.

function usage() {
    echo "Sample for rewriting an autogenerated eBPF lskel headers"
    echo "with a new signature"
    echo ""
    echo "USAGE: header_file sig"
    exit
}

ARGC=$#

EXPECTED_ARGS=2

if [ $ARGC -ne $EXPECTED_ARGS ] ; then
    usage
else
    SIG=$(xxd -p $2 | tr -d '\n' | sed 's/\(..\)/\\\\x\1/g')
    sed '/const char opts_sig/,/;/c\\tstatic const char opts_sig[] __attribute__((__aligned__(8))) = "\\\n'"$(printf '%s\n' "$SIG")"'\";' $1
fi
